/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as FinanceBalancesRouteImport } from './routes/finance.balances'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as InsuranceCompaniesRouteImport } from './routes/insurance.companies'
import { Route as InsuranceCoverageRouteImport } from './routes/insurance.coverage'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as ReportsInventoryRouteImport } from './routes/reports.inventory'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as SamplesIndexRouteImport } from './routes/samples.index'
import { Route as SamplesIdRouteImport } from './routes/samples.$id'
import { Route as SamplesNewRouteImport } from './routes/samples.new'
import { Route as SamplesTrackRouteImport } from './routes/samples.track'
import { Route as TestRequestsIndexRouteImport } from './routes/test-requests.index'
import { Route as TestRequestsNewRouteImport } from './routes/test-requests.new'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as TestsNewRouteImport } from './routes/tests.new'
import { Route as FinancePaymentsIndexRouteImport } from './routes/finance.payments.index'
import { Route as FinancePaymentsIdRouteImport } from './routes/finance.payments.$id'
import { Route as FinancePaymentsNewRouteImport } from './routes/finance.payments.new'
import { Route as InventoryReagentsNewRouteImport } from './routes/inventory.reagents.new'
import { Route as PatientsIdIndexRouteImport } from './routes/patients.$id.index'
import { Route as PatientsIdEditRouteImport } from './routes/patients.$id.edit'
import { Route as ResultsEnterSampleIdRouteImport } from './routes/results.enter.$sampleId'
import { Route as TestRequestsIdIndexRouteImport } from './routes/test-requests.$id.index'
import { Route as TestRequestsIdEditRouteImport } from './routes/test-requests.$id.edit'
import { Route as TestsCodeIndexRouteImport } from './routes/tests.$code.index'
import { Route as TestsCodeEditRouteImport } from './routes/tests.$code.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBalancesRoute = FinanceBalancesRouteImport.update({
  id: '/finance/balances',
  path: '/finance/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceCompaniesRoute = InsuranceCompaniesRouteImport.update({
  id: '/insurance/companies',
  path: '/insurance/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceCoverageRoute = InsuranceCoverageRouteImport.update({
  id: '/insurance/coverage',
  path: '/insurance/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsInventoryRoute = ReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesIndexRoute = SamplesIndexRouteImport.update({
  id: '/samples/',
  path: '/samples/',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesIdRoute = SamplesIdRouteImport.update({
  id: '/samples/$id',
  path: '/samples/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesNewRoute = SamplesNewRouteImport.update({
  id: '/samples/new',
  path: '/samples/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesTrackRoute = SamplesTrackRouteImport.update({
  id: '/samples/track',
  path: '/samples/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRequestsIndexRoute = TestRequestsIndexRouteImport.update({
  id: '/test-requests/',
  path: '/test-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRequestsNewRoute = TestRequestsNewRouteImport.update({
  id: '/test-requests/new',
  path: '/test-requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsNewRoute = TestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentsIndexRoute = FinancePaymentsIndexRouteImport.update({
  id: '/finance/payments/',
  path: '/finance/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentsIdRoute = FinancePaymentsIdRouteImport.update({
  id: '/finance/payments/$id',
  path: '/finance/payments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentsNewRoute = FinancePaymentsNewRouteImport.update({
  id: '/finance/payments/new',
  path: '/finance/payments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryReagentsNewRoute = InventoryReagentsNewRouteImport.update({
  id: '/inventory/reagents/new',
  path: '/inventory/reagents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdIndexRoute = PatientsIdIndexRouteImport.update({
  id: '/patients/$id/',
  path: '/patients/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdEditRoute = PatientsIdEditRouteImport.update({
  id: '/patients/$id/edit',
  path: '/patients/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsEnterSampleIdRoute = ResultsEnterSampleIdRouteImport.update({
  id: '/results/enter/$sampleId',
  path: '/results/enter/$sampleId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRequestsIdIndexRoute = TestRequestsIdIndexRouteImport.update({
  id: '/test-requests/$id/',
  path: '/test-requests/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRequestsIdEditRoute = TestRequestsIdEditRouteImport.update({
  id: '/test-requests/$id/edit',
  path: '/test-requests/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsCodeIndexRoute = TestsCodeIndexRouteImport.update({
  id: '/tests/$code/',
  path: '/tests/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsCodeEditRoute = TestsCodeEditRouteImport.update({
  id: '/tests/$code/edit',
  path: '/tests/$code/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/finance/balances': typeof FinanceBalancesRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/insurance/companies': typeof InsuranceCompaniesRoute
  '/insurance/coverage': typeof InsuranceCoverageRoute
  '/patients/new': typeof PatientsNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/results/$id': typeof ResultsIdRoute
  '/samples/$id': typeof SamplesIdRoute
  '/samples/new': typeof SamplesNewRoute
  '/samples/track': typeof SamplesTrackRoute
  '/test-requests/new': typeof TestRequestsNewRoute
  '/tests/new': typeof TestsNewRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/samples/': typeof SamplesIndexRoute
  '/test-requests/': typeof TestRequestsIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/finance/payments/$id': typeof FinancePaymentsIdRoute
  '/finance/payments/new': typeof FinancePaymentsNewRoute
  '/inventory/reagents/new': typeof InventoryReagentsNewRoute
  '/patients/$id/edit': typeof PatientsIdEditRoute
  '/results/enter/$sampleId': typeof ResultsEnterSampleIdRoute
  '/test-requests/$id/edit': typeof TestRequestsIdEditRoute
  '/tests/$code/edit': typeof TestsCodeEditRoute
  '/finance/payments/': typeof FinancePaymentsIndexRoute
  '/patients/$id/': typeof PatientsIdIndexRoute
  '/test-requests/$id/': typeof TestRequestsIdIndexRoute
  '/tests/$code/': typeof TestsCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/finance/balances': typeof FinanceBalancesRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/insurance/companies': typeof InsuranceCompaniesRoute
  '/insurance/coverage': typeof InsuranceCoverageRoute
  '/patients/new': typeof PatientsNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/results/$id': typeof ResultsIdRoute
  '/samples/$id': typeof SamplesIdRoute
  '/samples/new': typeof SamplesNewRoute
  '/samples/track': typeof SamplesTrackRoute
  '/test-requests/new': typeof TestRequestsNewRoute
  '/tests/new': typeof TestsNewRoute
  '/finance': typeof FinanceIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/results': typeof ResultsIndexRoute
  '/samples': typeof SamplesIndexRoute
  '/test-requests': typeof TestRequestsIndexRoute
  '/tests': typeof TestsIndexRoute
  '/finance/payments/$id': typeof FinancePaymentsIdRoute
  '/finance/payments/new': typeof FinancePaymentsNewRoute
  '/inventory/reagents/new': typeof InventoryReagentsNewRoute
  '/patients/$id/edit': typeof PatientsIdEditRoute
  '/results/enter/$sampleId': typeof ResultsEnterSampleIdRoute
  '/test-requests/$id/edit': typeof TestRequestsIdEditRoute
  '/tests/$code/edit': typeof TestsCodeEditRoute
  '/finance/payments': typeof FinancePaymentsIndexRoute
  '/patients/$id': typeof PatientsIdIndexRoute
  '/test-requests/$id': typeof TestRequestsIdIndexRoute
  '/tests/$code': typeof TestsCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/finance/balances': typeof FinanceBalancesRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/insurance/companies': typeof InsuranceCompaniesRoute
  '/insurance/coverage': typeof InsuranceCoverageRoute
  '/patients/new': typeof PatientsNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/results/$id': typeof ResultsIdRoute
  '/samples/$id': typeof SamplesIdRoute
  '/samples/new': typeof SamplesNewRoute
  '/samples/track': typeof SamplesTrackRoute
  '/test-requests/new': typeof TestRequestsNewRoute
  '/tests/new': typeof TestsNewRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/samples/': typeof SamplesIndexRoute
  '/test-requests/': typeof TestRequestsIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/finance/payments/$id': typeof FinancePaymentsIdRoute
  '/finance/payments/new': typeof FinancePaymentsNewRoute
  '/inventory/reagents/new': typeof InventoryReagentsNewRoute
  '/patients/$id/edit': typeof PatientsIdEditRoute
  '/results/enter/$sampleId': typeof ResultsEnterSampleIdRoute
  '/test-requests/$id/edit': typeof TestRequestsIdEditRoute
  '/tests/$code/edit': typeof TestsCodeEditRoute
  '/finance/payments/': typeof FinancePaymentsIndexRoute
  '/patients/$id/': typeof PatientsIdIndexRoute
  '/test-requests/$id/': typeof TestRequestsIdIndexRoute
  '/tests/$code/': typeof TestsCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/portal'
    | '/profile'
    | '/settings'
    | '/verify-otp'
    | '/finance/balances'
    | '/finance/reports'
    | '/insurance/companies'
    | '/insurance/coverage'
    | '/patients/new'
    | '/reports/$id'
    | '/reports/inventory'
    | '/results/$id'
    | '/samples/$id'
    | '/samples/new'
    | '/samples/track'
    | '/test-requests/new'
    | '/tests/new'
    | '/finance/'
    | '/inventory/'
    | '/patients/'
    | '/reports/'
    | '/results/'
    | '/samples/'
    | '/test-requests/'
    | '/tests/'
    | '/finance/payments/$id'
    | '/finance/payments/new'
    | '/inventory/reagents/new'
    | '/patients/$id/edit'
    | '/results/enter/$sampleId'
    | '/test-requests/$id/edit'
    | '/tests/$code/edit'
    | '/finance/payments/'
    | '/patients/$id/'
    | '/test-requests/$id/'
    | '/tests/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/portal'
    | '/profile'
    | '/settings'
    | '/verify-otp'
    | '/finance/balances'
    | '/finance/reports'
    | '/insurance/companies'
    | '/insurance/coverage'
    | '/patients/new'
    | '/reports/$id'
    | '/reports/inventory'
    | '/results/$id'
    | '/samples/$id'
    | '/samples/new'
    | '/samples/track'
    | '/test-requests/new'
    | '/tests/new'
    | '/finance'
    | '/inventory'
    | '/patients'
    | '/reports'
    | '/results'
    | '/samples'
    | '/test-requests'
    | '/tests'
    | '/finance/payments/$id'
    | '/finance/payments/new'
    | '/inventory/reagents/new'
    | '/patients/$id/edit'
    | '/results/enter/$sampleId'
    | '/test-requests/$id/edit'
    | '/tests/$code/edit'
    | '/finance/payments'
    | '/patients/$id'
    | '/test-requests/$id'
    | '/tests/$code'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/portal'
    | '/profile'
    | '/settings'
    | '/verify-otp'
    | '/finance/balances'
    | '/finance/reports'
    | '/insurance/companies'
    | '/insurance/coverage'
    | '/patients/new'
    | '/reports/$id'
    | '/reports/inventory'
    | '/results/$id'
    | '/samples/$id'
    | '/samples/new'
    | '/samples/track'
    | '/test-requests/new'
    | '/tests/new'
    | '/finance/'
    | '/inventory/'
    | '/patients/'
    | '/reports/'
    | '/results/'
    | '/samples/'
    | '/test-requests/'
    | '/tests/'
    | '/finance/payments/$id'
    | '/finance/payments/new'
    | '/inventory/reagents/new'
    | '/patients/$id/edit'
    | '/results/enter/$sampleId'
    | '/test-requests/$id/edit'
    | '/tests/$code/edit'
    | '/finance/payments/'
    | '/patients/$id/'
    | '/test-requests/$id/'
    | '/tests/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PortalRoute: typeof PortalRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  FinanceBalancesRoute: typeof FinanceBalancesRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  InsuranceCompaniesRoute: typeof InsuranceCompaniesRoute
  InsuranceCoverageRoute: typeof InsuranceCoverageRoute
  PatientsNewRoute: typeof PatientsNewRoute
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsInventoryRoute: typeof ReportsInventoryRoute
  ResultsIdRoute: typeof ResultsIdRoute
  SamplesIdRoute: typeof SamplesIdRoute
  SamplesNewRoute: typeof SamplesNewRoute
  SamplesTrackRoute: typeof SamplesTrackRoute
  TestRequestsNewRoute: typeof TestRequestsNewRoute
  TestsNewRoute: typeof TestsNewRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
  SamplesIndexRoute: typeof SamplesIndexRoute
  TestRequestsIndexRoute: typeof TestRequestsIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
  FinancePaymentsIdRoute: typeof FinancePaymentsIdRoute
  FinancePaymentsNewRoute: typeof FinancePaymentsNewRoute
  InventoryReagentsNewRoute: typeof InventoryReagentsNewRoute
  PatientsIdEditRoute: typeof PatientsIdEditRoute
  ResultsEnterSampleIdRoute: typeof ResultsEnterSampleIdRoute
  TestRequestsIdEditRoute: typeof TestRequestsIdEditRoute
  TestsCodeEditRoute: typeof TestsCodeEditRoute
  FinancePaymentsIndexRoute: typeof FinancePaymentsIndexRoute
  PatientsIdIndexRoute: typeof PatientsIdIndexRoute
  TestRequestsIdIndexRoute: typeof TestRequestsIdIndexRoute
  TestsCodeIndexRoute: typeof TestsCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/balances': {
      id: '/finance/balances'
      path: '/finance/balances'
      fullPath: '/finance/balances'
      preLoaderRoute: typeof FinanceBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/companies': {
      id: '/insurance/companies'
      path: '/insurance/companies'
      fullPath: '/insurance/companies'
      preLoaderRoute: typeof InsuranceCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/coverage': {
      id: '/insurance/coverage'
      path: '/insurance/coverage'
      fullPath: '/insurance/coverage'
      preLoaderRoute: typeof InsuranceCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/inventory': {
      id: '/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/': {
      id: '/samples/'
      path: '/samples'
      fullPath: '/samples/'
      preLoaderRoute: typeof SamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$id': {
      id: '/samples/$id'
      path: '/samples/$id'
      fullPath: '/samples/$id'
      preLoaderRoute: typeof SamplesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/new': {
      id: '/samples/new'
      path: '/samples/new'
      fullPath: '/samples/new'
      preLoaderRoute: typeof SamplesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/track': {
      id: '/samples/track'
      path: '/samples/track'
      fullPath: '/samples/track'
      preLoaderRoute: typeof SamplesTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-requests/': {
      id: '/test-requests/'
      path: '/test-requests'
      fullPath: '/test-requests/'
      preLoaderRoute: typeof TestRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-requests/new': {
      id: '/test-requests/new'
      path: '/test-requests/new'
      fullPath: '/test-requests/new'
      preLoaderRoute: typeof TestRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/new': {
      id: '/tests/new'
      path: '/tests/new'
      fullPath: '/tests/new'
      preLoaderRoute: typeof TestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payments/': {
      id: '/finance/payments/'
      path: '/finance/payments'
      fullPath: '/finance/payments/'
      preLoaderRoute: typeof FinancePaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payments/$id': {
      id: '/finance/payments/$id'
      path: '/finance/payments/$id'
      fullPath: '/finance/payments/$id'
      preLoaderRoute: typeof FinancePaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payments/new': {
      id: '/finance/payments/new'
      path: '/finance/payments/new'
      fullPath: '/finance/payments/new'
      preLoaderRoute: typeof FinancePaymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/reagents/new': {
      id: '/inventory/reagents/new'
      path: '/inventory/reagents/new'
      fullPath: '/inventory/reagents/new'
      preLoaderRoute: typeof InventoryReagentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/': {
      id: '/patients/$id/'
      path: '/patients/$id'
      fullPath: '/patients/$id/'
      preLoaderRoute: typeof PatientsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/edit': {
      id: '/patients/$id/edit'
      path: '/patients/$id/edit'
      fullPath: '/patients/$id/edit'
      preLoaderRoute: typeof PatientsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/enter/$sampleId': {
      id: '/results/enter/$sampleId'
      path: '/results/enter/$sampleId'
      fullPath: '/results/enter/$sampleId'
      preLoaderRoute: typeof ResultsEnterSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-requests/$id/': {
      id: '/test-requests/$id/'
      path: '/test-requests/$id'
      fullPath: '/test-requests/$id/'
      preLoaderRoute: typeof TestRequestsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-requests/$id/edit': {
      id: '/test-requests/$id/edit'
      path: '/test-requests/$id/edit'
      fullPath: '/test-requests/$id/edit'
      preLoaderRoute: typeof TestRequestsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$code/': {
      id: '/tests/$code/'
      path: '/tests/$code'
      fullPath: '/tests/$code/'
      preLoaderRoute: typeof TestsCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$code/edit': {
      id: '/tests/$code/edit'
      path: '/tests/$code/edit'
      fullPath: '/tests/$code/edit'
      preLoaderRoute: typeof TestsCodeEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PortalRoute: PortalRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  FinanceBalancesRoute: FinanceBalancesRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  InsuranceCompaniesRoute: InsuranceCompaniesRoute,
  InsuranceCoverageRoute: InsuranceCoverageRoute,
  PatientsNewRoute: PatientsNewRoute,
  ReportsIdRoute: ReportsIdRoute,
  ReportsInventoryRoute: ReportsInventoryRoute,
  ResultsIdRoute: ResultsIdRoute,
  SamplesIdRoute: SamplesIdRoute,
  SamplesNewRoute: SamplesNewRoute,
  SamplesTrackRoute: SamplesTrackRoute,
  TestRequestsNewRoute: TestRequestsNewRoute,
  TestsNewRoute: TestsNewRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
  SamplesIndexRoute: SamplesIndexRoute,
  TestRequestsIndexRoute: TestRequestsIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
  FinancePaymentsIdRoute: FinancePaymentsIdRoute,
  FinancePaymentsNewRoute: FinancePaymentsNewRoute,
  InventoryReagentsNewRoute: InventoryReagentsNewRoute,
  PatientsIdEditRoute: PatientsIdEditRoute,
  ResultsEnterSampleIdRoute: ResultsEnterSampleIdRoute,
  TestRequestsIdEditRoute: TestRequestsIdEditRoute,
  TestsCodeEditRoute: TestsCodeEditRoute,
  FinancePaymentsIndexRoute: FinancePaymentsIndexRoute,
  PatientsIdIndexRoute: PatientsIdIndexRoute,
  TestRequestsIdIndexRoute: TestRequestsIdIndexRoute,
  TestsCodeIndexRoute: TestsCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
